[palette]
base=#404552
text=#ffffffc8
window=#404552
window_text=#ffffffc8
button=#414654
button_text=#ffffffc8
highlight=#232c39
highlight_text=white
placeholder_text=#AFB8C5
link=#009DFF
link_visited=#9E4FFF
light=#5f677f
mid=#191919
dark=black

[window]
;window_shadow_brush=#80000000
;window_background_brush=$palette/window
window_border_brush=#61697c
;input_background_brush=$palette/base
;input_border_brush=$palette/highlight
input_trigger_color=$palette/placeholder_text
;input_hint_color=$palette/placeholder_text
;settings_button_color=$palette/button
;settings_button_highlight_color=$palette/highlight
;result_item_selection_background_brush=$palette/highlight
;result_item_selection_border_brush=$palette/highlight
;result_item_selection_text_color=$palette/highlight_text
;result_item_selection_subtext_color=$palette/placeholder_text
;result_item_text_color=$palette/window_text
;result_item_subtext_color=$palette/placeholder_text
;action_item_selection_background_brush=$palette/highlight
;action_item_selection_border_brush=$palette/highlight
;action_item_selection_text_color=$palette/highlight_text
;action_item_text_color=$palette/
