[display]
show_time = true
greeting = '''

███████╗ █████╗ ██████╗  ██████╗██╗  ██╗
╚══███╔╝██╔══██╗██╔══██╗██╔════╝██║  ██║
  ███╔╝ ███████║██████╔╝██║     ███████║
 ███╔╝  ██╔══██║██╔══██╗██║     ██╔══██║
███████╗██║  ██║██║  ██║╚██████╗██║  ██║
╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝

'''
align_greeting = "center"

[remember]
username = true
session = false
user_session = true

[secret]
mode = "characters"

[keybindings]
command = 2
sessions = 3
power = 4
background = 5

[background]
kind = "matrix"

[theme]
border = "bright-green"
text = "white"
time = "bright-green"
container = "black"
title = "bright-blue"
greet = "bright-blue"
prompt = "bright-blue"
input = "white"
action = "white"
button = "bright-green"

[session]
sessions_dirs = ["/usr/share/wayland-sessions", "/usr/share/xsessions"]
